include:
- template: Security/SAST.gitlab-ci.yml

stages:
  # - lint
  - test
  - deploy

# ... other jobs like build, lint, and test ...

sast:
  stage: test

run_unit_tests:
  stage: test
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - npm test
  only:
    - master

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - cdk diff
    - cdk deploy --require-approval never
  only:
    - master
