include:
- template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - test
  - deploy

# ... other jobs like build, lint, and test ...
lint_project:
  stage: lint
  image: node:latest
  before_script:
    - npm install
    - npm install --save-dev eslint typescript typescript-eslint
  script:
    - echo "npx eslint ."
  only:
    - main

sast:
  stage: test

run_unit_tests:
  stage: test
  image: node:latest
  before_script:
    - npm install -g aws-cdk
    - npm install
  script:
    - npm test
  only:
    - main

deploy:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g aws-cdk
    - npm install
  script:
    - cdk diff
    - cdk deploy --all --require-approval never
  only:
    - main
